### ISSUE TITLE
Bell state bitstring is off by one

### ISSUE THREAD

**Issue by stevenheidel** [QCGPU/qcgpu-rust#1]
This is really amazing work! I noticed something weird: when I run a two qubit bell state and sample it I see elements "00" and "100".

## Expected Behavior
Expected would be: "00" and "11" like in this example: https://qcgpu.github.io/qcgpu-rust/book/user-guide/examples.html

## Current Behavior
Currently returns: `Measured: {"00": 487, "100": 513}`

## Steps to Reproduce (for bugs)
```rust
extern crate qcgpu;

use qcgpu::State;

fn main() {
    let num_gates = 2;
    let mut state = State::new(num_gates, 0);

    state.h(0);
    for i in 0..num_gates as i32 {
        state.cx(i, i + 1);
    }

    println!("Measured: {:?}", state.measure_many(1000));
}
```

## Your Environment
* rustc 1.25.0 (84203cac6 2018-03-25)
* qcgpu-rust on latest master

**Comment by adamisntdead** [comment]
Thanks for the feedback! 
I think your code might be slightly off! that for loop will go through 0, 1, which means the simulator is trying to apply a CNOT with the control of 0 and target of 1, and then a control of 1 and a target of 2! The qubits are zero indexed, so you are actually trying to apply the gate to a qubit that isn't there, that's why the results are off!

I changed the code slightly, I think this should be more correct:

```rust
extern crate qcgpu;

use qcgpu::State;

fn main() {
    let num_gates = 2;
    let mut state = State::new(num_gates, 0);

    state.h(0);
    for i in 0..(num_gates - 1) as i32 {
        state.cx(i, i + 1);
    }

    println!("Measured: {:?}", state.measure_many(1000));
}
```

Which outputted:

```
Measured: {"00": 491, "11": 509}
```
